version: '3'

services:

  ws-node-demo:
    restart: always
    build:
      context: ./.
      dockerfile: ./Dockerfile.dev
    image: local-ws-node-book-bend-dev:latest
    command: ['npm', 'run', 'start:dev']
    container_name: ws-node-book-bend-container
    environment:
        - loglevel=none
    links:
        - "mongo:mongo"
    working_dir: "/usr/src/app"
    volumes:
        - "./.:/usr/src/app"
        - "/usr/src/app/node_modules"
    ports:
        - "8080:8080"
        - "5858:5858"
  mongo:
    image: mongo:3.4
    volumes:
    - ../db-data/mongo-data:/data/db
    ports:
    - "27017:27017"

  redis:
    image: 'bitnami/redis:5.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - ../db-data/redis-data:/bitnami/redis/data

