express:
    port: 8080
    debug: 5858
    host: ws-node-book-bin

auth:
    jwt_secret: 'UR4swimlane$'
    jwt_short_time_secret: 'M@S0m3NU$'

mongo:
    urlClient: 'mongodb://127.0.0.1:27017/book-bin'
    urlDocker: 'mongodb://mongodb-primary:27017/book-bin?replicaSet=bookBinRS'

redis:
    TTL: 86400
    port: 6379
    urlDocker: 'redis://tokenholder'





# none/debug/info
loglevel: info
