express:
    port: 8080
    debug: 5858
    host: ws-node-book-bin

auth:
    jwt_secret: 'UR4swimlane$'
    jwt_short_time_secret: 'M@S0m3NU$'

mongo:
    urlClient: 'mongodb://127.0.0.1:27017/book-bin?replicaSet=bookBinRS'
    urlDocker: 'mongodb://mongodb-primary:27017/book-bin?replicaSet=bookBinRS'

redis:
    TTL: 86400
    port: 6379
    urlDocker: 'redis://tokenholder'

waitlist_opp:
    TTE: 60 #seconds

#    tenDayMS:7*24*60*60*1000,
#    //dev fun 2Hours
#    twoHrMS:2*60*60*1000,
#    //dev fun 10 minutes
#    tenMinMS:10*60*1000,
#    //wait time for response from waitlist request
#    twoMinMS: 2*60*1000,
borrow_time:
    ttE: 'twoHrMS'





# none/debug/info
loglevel: info
